### ISSUE TITLE
Конфигурация сервера для нескольких сайтов на одной машине

### ISSUE THREAD

**Issue by markpolyak** [nwebiestudio/mspolyak-website#10]
Например, см. https://dolphinandmermaids.com/blog/docker-nginx-letsencrypt/

Настройка nginx для поддержки нескольких сайтов на одном сервере (без использования докера, т.е. нам не подходит):
https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-server-blocks-virtual-hosts-on-ubuntu-16-04
https://serverspace.io/support/help/nginx-virtual-hosts-on-ubuntu-20-04/

DNS-записи для поддоменов делаются в консоли хостинга (вкладка Мои домены / DNS у SWeb). С точки зрения nginx, каждый поддомен - это отдельный сайт

**Comment by Gufderald** [comment]
Реализовано через nginx-proxy&letsencrypt-companion (1 ссылка)
